#index:
#    path: /
#    controller: App\Controller\DefaultController::index
material_dashboard:
    # loads routes from the given routing file stored in some bundle
    resource: '@MaterialDashboardBundle/Resources/config/routing.yaml'